name: Build Docker

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  IMAGE_TAG: ${{ github.repository }}/rssnotifier:lastest

jobs:
  build:
    name: 'Build Docker image'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and Push Docker image'
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./backend
          push: true
          labels: ${{ steps.meta_backend.outputs.labels }}
          tags: ${{ env.IMAGE_TAG }}